# Generated by Django 5.0.2 on 2024-04-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='carusol_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
                ('title3', models.CharField(max_length=50)),
                ('title4', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusol/')),
            ],
        ),
    ]
