# Generated by Django 5.0.2 on 2024-03-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='my_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=50, null=True)),
                ('house_number', models.TextField(blank=True, max_length=50, null=True)),
                ('road_number', models.TextField(blank=True, max_length=50, null=True)),
                ('thana', models.TextField(blank=True, max_length=50, null=True)),
                ('post_office', models.TextField(blank=True, max_length=50, null=True)),
                ('phone_no', models.TextField(blank=True, max_length=50, null=True)),
                ('town', models.TextField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
